server:
  port: 9090
  servlet:
    context-path: /my-backend/v1

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true